### PR TITLE
fvm method bug fix

### PR DESCRIPTION
**Pull request by mmcgurn**
fixes a bug in the finite volume and adds tests to capture it.

### CODE REVIEW

**Review by pkrull-ansys — APPROVED** [review]
Nice integration tests!

**Review by knepley — COMMENTED** [review]
@mmcgurn This looks like it pairs with PETSc changes for GetFaceFields. Can you point me to the branch?

**Comment by mmcgurn** [comment]
> @mmcgurn This looks like it pairs with PETSc changes for GetFaceFields. Can you point me to the branch?

I have a custom method for GetFaceFields in ablate.
https://github.com/UBCHREST/ablate/blob/1d5b87fc76f77293d95e4fdad952d358f1d45141/ablateCore/flow/fvSupport.c#L184

**Comment by knepley** [comment]
@mmcgurn That is great! We should just make this the PETSc version.

**Pull request merged**
