### PR TITLE
updating the Dakota doc header

### PR DESCRIPTION
**Pull request by danial-faghihi**

### CODE REVIEW

**Comment by mmcgurn** [comment]
@danial-faghihi Thank you for making that change.  You don't need to close and reopen a PR, just push your changes to your branch and the PR will update.  The tests failed the version check, so you will have to update the CMakeLists.txt file to 

```cmake
project(ablateLibrary VERSION 0.8.1)
```

**Comment by danial-faghihi** [comment]
@mmcgurn just changed the CMakeLists.txt and pushed the changes into my branch.

**Comment by mmcgurn** [comment]
> @mmcgurn just changed the CMakeLists.txt and pushed the changes into my branch.

@danial-faghihi Thanks!  The tests are now rerunning.

**Review by mmcgurn — APPROVED** [review]
Thanks! Looks good.  You should now be able to squash and merge the PR.

**Pull request merged**
