### PR TITLE
added support for constants and random number in formula classes

### LINKED ISSUE #341: mathFunctions::ParsedSeries
The ParsedSeries need to be adopted so it can get " constants" and generate "random" numbers.

### PR DESCRIPTION
**Pull request by mmcgurn**
This should close #341 .  @Rozie100 would you mind taking a look to see if it addresses your needs?

### CODE REVIEW

**Comment by Rozie100** [comment]
Thanks for adding this support!

**Comment by mmcgurn** [comment]
> Thanks for adding this support!

Thanks!  If this is enough functionality can you approve the pr?

**Comment by Rozie100** [comment]
It should do it, Thanks!

**Review by Rozie100 — APPROVED** [review]

**Comment by Rozie100** [comment]
Sorry for the delay, I have a bad connection at the hotel.

**Pull request merged**
