### PR TITLE
PR for DAKOTA-ABLATE integration doc

### PR DESCRIPTION
**Pull request by ajbecerr**
2 commits.

First:

- Fixed some typos (ABALATE, ABALTE, etc.)
- Modified driver.py (to resolve MPI issue)
- Changed "reaction rate constants" to "activation energies" in line 54 (We do not directly perturb the reaction rate constants. By the Arrhenius equation, each reaction rate constant is related to multiple parameters including activation energy. In a more robust framework, we would perturb each of these parameters and analyze their effect on ignition delay. However, in the example, only the activation energies are perturbed).

Is it also worth including the lines below (which are mostly CCR specific)?

module purge;
module load dakota/6.15
export DAK_INSTALL=/util/academic/dakota/dakota-6.15.0-release-public-rhel7.x86_64-gui_cli
export PATH=$DAK_INSTALL/bin:$DAK_INSTALL/share/dakota/test:$PATH
export PYTHONPATH=$DAK_INSTALL/share/dakota/Python:$PYTHONPATH

Second:

- Updated estimated sensitivity indices for the two parameters to reflect most recent computation (these values may always vary slightly due to sampling methods)
- Added self-explanatory comments back to driver.py (accidental removal in previous commit)

### CODE REVIEW

**Review by mmcgurn — APPROVED** [review]
Thanks @ajbecerr for the documentation update.  You will need to bump the project version the root cmakelists file.  You may also need to rebase/merge in the main branch changes before you complete the PR.  Please let me know if you have any questions or need any help.

**Comment by mmcgurn** [comment]
@ajbecerr This looks like the PR is ready to be merged.  When you are ready can you squash and merge?  Thanks!

**Comment by ajbecerr** [comment]
@mmcgurn, excellent. I am ready to squash and merge, but I do not currently have write access to the repo.

**Comment by mmcgurn** [comment]
@ajbecerr I've invited you to the center.  Once you accept you should be able to merge.  Thanks!

**Pull request merged**
